language: python

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"

env:
  - DJANGO="django>=1.5,<1.6"
  - DJANGO="django>=1.6,<1.7"
  - DJANGO="django>=1.7,<1.8"
  - DJANGO="django>=1.8,<1.9"
  - DJANGO="django>=1.9,<1.10"

matrix:
  exclude:
    - python: "2.6"
      env: DJANGO="django>=1.7,<1.8"
    - python: "2.6"
      env: DJANGO="django>=1.8,<1.9"
    - python: "2.6"
      env: DJANGO="django>=1.9,<1.10"
    - python: "3.3"
      env: DJANGO="django>=1.9,<1.10"
    - python: "3.5"
      env: DJANGO="django>=1.5,<1.6"
    - python: "3.5"
      env: DJANGO="django>=1.6,<1.7"
    - python: "3.5"
      env: DJANGO="django>=1.7,<1.8"

install:
  - pip install -r requirements_test.txt
  - pip install coveralls
  - pip install $DJANGO

script:
  - coverage run setup.py test

after_success:
  - coveralls

notifications:
  email:
    - vinta.chen@gmail.com
